Repository cse112-sp22-group3/rocketrecipes, pull requests merged in 2022-05, with the labels that each got.

#5 TeamRocket#3: Pipeline Refinement
  .github/workflows/deploy.yml
  .github/workflows/jsdocs-main.yml
  .github/workflows/jsdocs-pr.yml
  README.md
  testing/e2e/home.test.js
  testing/e2e/myAccount.test.js
  testing/e2e/recipePage.test.js
  testing/e2e/search.test.js
Labels: ci/cd, multiple collaborators

#13 TEAMROCKET#11: Initial Testing Refinement
  testing/e2e/createRecipe.test.js
  testing/e2e/favoriteRecipe.test.js
  testing/e2e/home.test.js
  testing/e2e/myAccount.test.js
  testing/e2e/navigation.test.js
  testing/e2e/recipePage.test.js
  testing/e2e/search.test.js
  testing/unit/utilsTesting.test.js
Labels: multiple collaborators, testing

#52 NO-TICKET: Fix negative scaling
  root/components/recipe-card.js
  root/scripts/recipepage.js
Labels: bug

#51 TEAMROCKET#33: User login/sign up page
  root/components/custom-navbar.js
  root/css/entry.css
  root/html/entry.html
  root/scripts/auth.js
Labels: UI

#53 TEAMROCKET#17: Firebase Data Model
  docs/firebase_datamodel.md
Labels: documentation, POC

#58 TEAMROCKET#52: Ingredient Checklist
  .eslintrc.js
  favicon.png
  package-lock.json
  package.json
  root/components/custom-navbar.js
  root/components/custom-searchbar.js
  root/css/CreateRecipe.css
  root/css/RecipePage.css
  root/css/entry.css
  root/css/generalAccount.css
  root/css/global.css
  root/css/homeStyle.css
  root/css/search.css
  root/html/RecipePage.html
  root/html/SearchPage.html
  root/html/index.html
  root/media/header-logo.png
  root/media/nav_background.png
  root/scripts/recipepage.js
  root/scripts/searchpage.js
  testing/e2e/navigation.test.js
Labels: enhancement, help wanted, UI
